# Site settings
name: Denominational Bitcoin Wallets
title: Denominational Bitcoin Wallets
email: ajkochanowicz@gmail.co
description: Printable Bitcoin Wallets in fixed denominations set in beautiful design.
username: ajkochanowicz
twitter_username: yourwebsitesUX
# Once Github updates to Jekyll 2, change baseurl to ""
baseurl: "/bitcoinbills"
url: "http://ajkochanowicz.github.io/bitcoinbills/"

# Build settings
markdown: kramdown
permalinks: pretty
sass:
  sass_dir: _sass
