# Site settings
name: Dat site title tho
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
# Once Github updates to Jekyll 2, change baseurl to ""
baseurl: "/bitcoinbills"
url: "http://ajkochanowicz.github.io/bitcoinbills/"

# Build settings
markdown: kramdown
permalinks: pretty
sass:
  sass_dir: css
